export const PROCESS_IMAGE_START = 'PROCESS_IMAGE_START';
export const PROCESS_IMAGE_ERROR = 'PROCESS_IMAGE_ERROR';
export const PROCESS_IMAGE_COMPLETE = 'PROCESS_IMAGE_COMPLETE';

export const FORM_IMAGE_START = 'FORM_IMAGE_START';
export const FORM_IMAGE_ERROR = 'FORM_IMAGE_ERROR';
export const FORM_IMAGE_COMPLETE = 'FORM_IMAGE_COMPLETE';